import Foundation

/// Owns the short-lived OpenSSH configuration shared by an interactive SSH
/// process and its SFTP helpers. The file contains routing metadata only; it
/// never contains a password.
public final class SSHRouteConfiguration: @unchecked Sendable {
    public let directoryURL: URL
    public let fileURL: URL
    public let targetAlias: String

    private let route: ResolvedSSHRoute

    public init(route: ResolvedSSHRoute, sessionID: UUID = UUID()) throws {
        self.route = route
        let shortSessionID = sessionID.uuidString
            .replacingOccurrences(of: "-", with: "")
            .prefix(12)
        let directoryURL = URL(fileURLWithPath: "/private/tmp", isDirectory: true)
            .appendingPathComponent("mx-\(shortSessionID)", isDirectory: true)
        try FileManager.default.createDirectory(
            at: directoryURL,
            withIntermediateDirectories: false,
            attributes: [.posixPermissions: 0o700]
        )

        let fileURL = directoryURL.appendingPathComponent("ssh_config", isDirectory: false)
        self.directoryURL = directoryURL
        self.fileURL = fileURL
        self.targetAlias = Self.alias(for: route.target)

        do {
            try Self.write(Self.makeConfig(route: route, directoryURL: directoryURL), to: fileURL)
        } catch {
            try? FileManager.default.removeItem(at: directoryURL)
            throw error
        }
    }

    deinit {
        try? FileManager.default.removeItem(at: directoryURL)
    }

    public func alias(for profile: SSHProfile) -> String {
        Self.alias(for: profile)
    }

    public func containsPasswordProfile() -> Bool {
        route.profiles.contains {
            if case .password = $0.authentication { return true }
            return false
        }
    }

    private static func makeConfig(
        route: ResolvedSSHRoute,
        directoryURL: URL
    ) throws -> String {
        var lines = [
            "# Generated by osXterm. Do not edit.",
            "Host *",
            "    StrictHostKeyChecking accept-new",
            "    ControlMaster auto",
            "    ControlPersist no",
            "    ControlPath \(directoryURL.appendingPathComponent("c-%C").path)",
            ""
        ]

        let aliases = route.profiles.map(Self.alias)
        for (index, profile) in route.profiles.enumerated() {
            guard let target = SSHConnectionTarget.parse(
                host: profile.host,
                username: profile.username
            ) else {
                throw SSHRouteConfigurationError.invalidProfile(profile.id)
            }
            guard (1 ... 65_535).contains(profile.port) else {
                throw SSHRouteConfigurationError.invalidPort(profile.id)
            }
            guard isSafeConfigValue(target.host), isSafeConfigValue(target.username) else {
                throw SSHRouteConfigurationError.invalidProfile(profile.id)
            }

            lines.append("Host \(aliases[index])")
            lines.append("    HostName \(target.host)")
            lines.append("    User \(target.username)")
            lines.append("    Port \(profile.port)")
            lines.append("    BatchMode no")

            switch profile.authentication {
            case let .agent(socketPath):
                if let socketPath {
                    guard isSafeConfigValue(socketPath) else {
                        throw SSHRouteConfigurationError.invalidProfile(profile.id)
                    }
                    lines.append("    IdentityAgent \(socketPath)")
                }
                lines.append("    PreferredAuthentications publickey")
                lines.append("    PasswordAuthentication no")
                lines.append("    KbdInteractiveAuthentication no")

            case let .identityFile(path):
                guard isSafeConfigValue(path) else {
                    throw SSHRouteConfigurationError.invalidProfile(profile.id)
                }
                lines.append("    IdentityFile \(path)")
                lines.append("    IdentitiesOnly yes")
                lines.append("    PreferredAuthentications publickey")
                lines.append("    PasswordAuthentication no")
                lines.append("    KbdInteractiveAuthentication no")

            case .password:
                lines.append("    PreferredAuthentications keyboard-interactive,password")
                lines.append("    PubkeyAuthentication no")
                lines.append("    NumberOfPasswordPrompts 1")
            }

            if let proxy = profile.proxy {
                lines.append("    ProxyCommand \(try proxyCommand(proxy))")
            }

            if index < route.hops.count {
                let nestedJumpAliases = Array(aliases.prefix(index))
                if !nestedJumpAliases.isEmpty {
                    lines.append("    ProxyJump \(nestedJumpAliases.joined(separator: ","))")
                }
            }
            lines.append("")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    private static func write(_ contents: String, to url: URL) throws {
        try Data(contents.utf8).write(to: url, options: [.atomic])
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o600],
            ofItemAtPath: url.path
        )
    }

    private static func alias(for profile: SSHProfile) -> String {
        "osxterm-" + profile.id.uuidString.lowercased()
    }

    private static func isSafeConfigValue(_ value: String) -> Bool {
        !value.isEmpty
            && !value.contains("\0")
            && !value.contains("\n")
            && !value.contains("\r")
    }

    private static func proxyCommand(_ proxy: SSHProxy) throws -> String {
        let host: String
        let port: Int
        let mode: String
        let username: String?
        switch proxy {
        case let .http(proxyHost, proxyPort, proxyUsername):
            host = proxyHost
            port = proxyPort
            mode = "connect"
            username = proxyUsername
        case let .socks5(proxyHost, proxyPort, proxyUsername):
            host = proxyHost
            port = proxyPort
            mode = "5"
            username = proxyUsername
        }

        guard (1 ... 65_535).contains(port), isSafeProxyValue(host) else {
            throw SSHRouteConfigurationError.invalidProxy
        }
        if let username, !isSafeProxyValue(username) {
            throw SSHRouteConfigurationError.invalidProxy
        }
        let endpointHost = host.contains(":") && !host.hasPrefix("[") ? "[\(host)]" : host
        let endpoint = "\(shellQuote(endpointHost)):\(port)"
        var command = "/usr/bin/nc -X \(mode) -x \(endpoint)"
        if let username {
            command += " -P \(shellQuote(username))"
        }
        command += " %h %p"
        return command
    }

    private static func isSafeProxyValue(_ value: String) -> Bool {
        !value.isEmpty
            && !value.contains("\0")
            && !value.contains("\n")
            && !value.contains("\r")
            && !value.unicodeScalars.contains(where: { CharacterSet.whitespacesAndNewlines.contains($0) })
    }

    private static func shellQuote(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}

public enum SSHRouteConfigurationError: Error, Equatable, Sendable {
    case invalidProfile(UUID)
    case invalidPort(UUID)
    case invalidProxy
}

extension SSHRouteConfigurationError: LocalizedError {
    public var errorDescription: String? {
        switch self {
        case let .invalidProfile(id):
            "The SSH route contains invalid profile \(id.uuidString)."
        case let .invalidPort(id):
            "The SSH route contains an invalid port in profile \(id.uuidString)."
        case .invalidProxy:
            "The SSH route contains an invalid proxy configuration."
        }
    }
}
